### ISSUE TITLE
Set your personal goals

### ISSUE THREAD

**Issue by nicoolas25** [Markentoine/koeditor#1]
* Why this project?
* What motivate you?
* How does this project fits into your life?
* How much time do you want to invest in this and for how long?
* What is the criteria that will tell you that you succeeded?

**Comment by Markentoine** [comment]
**Why this project?**
This project intends to solve several problems I encounter during writing sessions with students like:
* ***commitment***: improve engagement for students by pairing or working differently when it comes to writing from scratch.
* ***efficiency***: improve help and advice I can give on the fly during the session
* ***evaluation of work with others***: without stats, it’s difficult to differentiate the one who really worked from the one who just stared at the work.
* ***vary the activities around writing***: it’s difficult to propose different activities through an entire group with different levels of mastery

This project is also a way to **put my fresh skills on the test**; a way to **challenge** myself; give myself a "Capstone" to perfect my training.

**Comment by Markentoine** [comment]
**What motivates me?**

* I want to set the bar higher than my actual skills can reach. My core skill:  learning and **pushing the boundaries**. That’s always the main force that pushes me forward. So, I know that I will find reasons to move on if I'm facing what I consider a challenge.

* The second incentive is the **produce something tangible**, that exists in the outer world, meaning outside of my head.

**Comment by Markentoine** [comment]
**How this project fits into my life?**

Since two years now, I dedicate a good portion of my life to gain new skills in this domain, so the project seems **in line with the trajectory my life has followed until now**.

**Comment by Markentoine** [comment]
**How much time do I want to invest in this and for how long?**

Following on from the previous statement on my lifestyle, I would say that I can spend about **20 hours a week on the whole project on average**. I can work there quite regularly because I am now used to studying almost 3 hours a day. As I have extra time thanks to my "food job" I can also make more effort from time to time, which means for example that I can work full time during my holidays, every 6- 7 weeks.

I am mentally prepared to put **one year** at least in this project.

**Comment by Markentoine** [comment]
**What are the criteria that will tell me that I succeeded?**

* Have shipped **a piece of software that works**
* Have produced **something useful for me as a teacher**
* Have built **helpful something for students and other people** they can access freely and easily.

**Comment by nicoolas25** [comment]
Very clear, thank you for taking the time to state all that.
